// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC_YASF79jFfsouml8ySSFZRz-eiurHao',
    appId: '1:300687956824:web:d48ff58680461834dea32d',
    messagingSenderId: '300687956824',
    projectId: 'computerclubbase',
    authDomain: 'computerclubbase.firebaseapp.com',
    storageBucket: 'computerclubbase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMgplrR1Sn6ExxUClRdAEChiPv1ZHDlIA',
    appId: '1:300687956824:android:bd962ce6490a8b6bdea32d',
    messagingSenderId: '300687956824',
    projectId: 'computerclubbase',
    storageBucket: 'computerclubbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3rZpPF277A4PGgA0rI5lNFUGVtM2P-o4',
    appId: '1:300687956824:ios:ed7e10a5b403a8a5dea32d',
    messagingSenderId: '300687956824',
    projectId: 'computerclubbase',
    storageBucket: 'computerclubbase.firebasestorage.app',
    iosBundleId: 'com.example.computerClubVladimir',
  );
}
